#
# Dependencies for smlm analysis
#
# Create new environment: conda env create --file "./environment.yml"
# Update existing environment: conda env update --file "./environment.yml"
#
channels:
- conda-forge
- defaults

dependencies:
# Python
- cython
- pip
- tqdm
- qtpy!=2.3.0

# Python tests
- pytest

# Scientific python
- numpy>1.17.0
- pandas
- scipy
- scikit-learn
- scikit-image
- matplotlib
- networkx
- shapely!=2.0.0,!=2.0.1
- lmfit

# Google
- protobuf

# File formats
- ruamel.yaml
- tifffile
- asdf
- # only needed for python < 3.11:
- tomli>=1.1.0

# Data analysis tools
- boost-histogram
- fast-histogram

# Extra requirements
- hdbscan
- colorcet
- trackpy

# More
- jupyterlab
- plotly

- pip:
    - open3d!=0.12.0
#    - locan==0.14
